title: Shamil Ibrahim
author: GitHub User
email: shamilibrahimk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An Entry Level Programmer Exploring The Code World.

# social links
twitter_username: shamilibrahik
github_username:  shamilibrahim

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
